version: '3'

networks:
  ml_assignment:
    external: true

services:
  ml_fe:
    image: ml_fe
    container_name: ml_fe
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - ml_assignment